#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_USER" <<-EOSQL
    CREATE USER $POSTGRES_GAME_USER WITH ENCRYPTED PASSWORD '$POSTGRES_GAME_PASSWORD';
    CREATE DATABASE $POSTGRES_GAME_DB OWNER $POSTGRES_GAME_USER;

    CREATE USER $POSTGRES_KC_USER WITH ENCRYPTED PASSWORD '$POSTGRES_KC_PASSWORD';
    CREATE DATABASE $POSTGRES_KC_DB OWNER $POSTGRES_KC_USER;
EOSQL