services:
  # database:
  #   image: postgres:16-alpine
  #   container_name: bombermann-database
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
  #       ]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  app:
    build: .
    container_name: bombermann-app
    volumes:
      - ./backend:/app/backend
      - ./utils:/app/utils
      - /app/node_modules
      - /app/backend/public
    ports:
     - "${BACKEND_PORT}:3001"
#   depends_on:
#      - database
    environment:
      FRONTEND_URL: "http://localhost:3001"
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      SESSION_SECRET: ${SESSION_SECRET}
volumes:
  postgres_data: